name: fluent_reader_lite
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+11

environment:
  sdk: ">=2.7.0 <2.12.0"  # 保持较低版本范围

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0  # 使用与较低版本 Dart 兼容的版本
  tuple: ^1.0.3  # 回滚到不包含空安全特性的版本
  shared_preferences: ^0.5.12+4  # 使用与较低版本 Dart 兼容的版本
  intl: ^0.16.1  # 使用与较低版本 Dart 兼容的版本
  http: ^0.12.2  # 使用与较低版本 Dart 兼容的版本
  html: ^0.14.0+4  # 使用与较低版本 Dart 兼容的版本
  webview_flutter: ^1.0.7  # 使用与较低版本 Dart 兼容的版本
  jaguar: ^2.8.14  # 使用与较低版本 Dart 兼容的版本
  jaguar_flutter_asset: ^2.0.0  # 使用与较低版本 Dart 兼容的版本
  url_launcher: ^5.7.10  # 使用与较低版本 Dart 兼容的版本
  sqflite: ^1.3.2+1  # 更新为与较低版本 Dart 兼容的版本
  path: ^1.7.0  # 使用不带空安全特性的版本
  share: ^0.6.5+4  # 使用与较低版本 Dart 兼容的版本
  package_info_plus: ^1.0.6  # 使用与较低版本 Dart 兼容的版本
  crypto: ^2.1.5  # 使用与较低版本 Dart 兼容的版本
  responsive_builder: ^0.4.0  # 更新为与较低版本 Dart 兼容的版本
  cached_network_image: ^2.5.0  # 使用与较低版本 Dart 兼容的版本
  flutter_cache_manager: ^2.1.1  # 使用与较低版本 Dart 兼容的版本
  lpinyin: ^1.0.3  # 使用与较低版本 Dart 兼容的版本
  uni_links: ^0.4.0  # 使用与较低版本 Dart 兼容的版本
  modal_bottom_sheet: ^1.0.0-pre  # 使用与较低版本 Dart 兼容的版本
  overlay_dialog: ^0.2.0
  cupertino_icons: ^0.1.3  # 使用与较低版本 Dart 兼容的版本

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/article/
    - assets/icons/

flutter_intl:
  enabled: true
