name: fluent_reader_lite
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+11

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.3
  tuple: ^2.0.0
  shared_preferences: ^2.0.15
  intl: ^0.19.0
  http: ^0.13.4
  html: ^0.15.0
  webview_flutter: ^3.0.4
  jaguar: ^3.0.11
  jaguar_flutter_asset: ^3.0.0
  url_launcher: ^6.0.9
  sqflite: ^2.0.0+3
  path: ^1.8.0
  share: ^2.0.4
  package_info_plus: ^4.1.0
  crypto: ^3.0.1
  responsive_builder: ^0.4.1
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.0
  lpinyin: ^2.0.3
  uni_links: ^0.5.1
  modal_bottom_sheet: ^3.0.0-pre
  overlay_dialog: ^0.2.0
  flutter_tts: ^3.8.5


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/article/
    - assets/icons/

flutter_intl:
  enabled: true
